### ISSUE TITLE
Start error (Exception in thread "main")

### ISSUE THREAD

**Issue by reptile023** [ericek111/java-csgo-externals#6] opened 2017-08-19 19:38 UTC
> Exception in thread "main" com.jogamp.opengl.GLException: main: No OpenGL context current on this thread
> 	at com.jogamp.opengl.GLContext.getCurrentGL(GLContext.java:510)
> 	at com.jogamp.opengl.util.awt.TextureRenderer.init(TextureRenderer.java:619)
> 	at com.jogamp.opengl.util.awt.TextureRenderer.<init>(TextureRenderer.java:139)
> 	at com.jogamp.opengl.util.awt.TextureRenderer.<init>(TextureRenderer.java:130)
> 	at me.lixko.csgoexternals.util.Texture.<init>(Texture.java:25)
> 	at me.lixko.csgoexternals.util.DrawUtils.addTexture(DrawUtils.java:85)
> 	at me.lixko.csgoexternals.util.DrawUtils.initializeTextures(DrawUtils.java:41)
> 	at me.lixko.csgoexternals.Engine.init(Engine.java:43)
> 	at me.lixko.csgoexternals.Main.main(Main.java:21)

What can i do?

**Comment by DrInsidious** [comment] 2017-08-19 19:59
same problem :/ fix?

**Comment by DrInsidious** [comment] 2017-08-19 20:00
valve prob fixed this cheat

**Comment by reptile023** [comment] 2017-08-19 20:11
There are no fixes already, im waiting for a comment from the dev.

**Comment by Rad0N-2nn** [comment] 2017-08-19 21:20
Same here :S

**Comment by ericek111** [comment] 2017-08-19 23:44
Hello,
this issue was fixed with [release 2.0.1](https://github.com/ericek111/java-csgo-externals/releases/tag/2.0.1). It was caused by textures being loaded before OpenGL initialization. Thank you all for the issue report!

**Closed as completed by ericek111** 2017-08-19 23:44 UTC
